services:
  db:
    build:
      context: ./Database
      dockerfile: .dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}               
      POSTGRES_USER: ${POSTGRES_USER_MASTER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_MASTER}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: